"""Tests for git-tracked projections module.

Tests cover:
- generate_decisions_md: Active decisions markdown generation
- generate_archive_md: Archived decisions markdown generation
- generate_plan_md: Active plan markdown generation
- regenerate_all: Full projection regeneration
- should_regenerate: Regeneration check logic
- ProjectionStats: Statistics dataclass
"""

from pathlib import Path

import pytest

from cortex.config import CortexConfig
from cortex.models import Event, EventType
from cortex.store import EventStore

# =============================================================================
# Fixtures
# =============================================================================


@pytest.fixture
def tmp_project(tmp_path: Path) -> Path:
    """Create a temporary project directory."""
    project_dir = tmp_path / "test-project"
    project_dir.mkdir()
    return project_dir


@pytest.fixture
def tmp_cortex_home(tmp_path: Path) -> Path:
    """Create a temporary cortex home directory."""
    cortex_home = tmp_path / ".cortex"
    cortex_home.mkdir()
    return cortex_home


@pytest.fixture
def sample_events() -> list[Event]:
    """Sample events for testing projections."""
    return [
        Event(
            type=EventType.DECISION_MADE,
            content="Use SQLite for storage because it's zero-config.",
            confidence=1.0,
            salience=1.0,
            immortal=True,
            git_branch="main",
            created_at="2026-02-14T10:00:00Z",
        ),
        Event(
            type=EventType.APPROACH_REJECTED,
            content="Rejected PostgreSQL - overkill for single-user use case.",
            confidence=1.0,
            salience=1.0,
            immortal=True,
            git_branch="main",
            created_at="2026-02-14T09:00:00Z",
        ),
        Event(
            type=EventType.PLAN_CREATED,
            content="1. Implement feature X\n2. Write tests\n3. Deploy",
            confidence=0.9,
            salience=0.9,
            immortal=False,
            git_branch="main",
            created_at="2026-02-14T11:00:00Z",
        ),
        Event(
            type=EventType.PLAN_STEP_COMPLETED,
            content="Implement feature X",
            confidence=1.0,
            salience=0.5,
            immortal=False,
            git_branch="main",
            created_at="2026-02-14T12:00:00Z",
        ),
        Event(
            type=EventType.FILE_MODIFIED,
            content="Modified src/main.py",
            confidence=1.0,
            salience=0.5,
            immortal=False,
            git_branch="main",
            created_at="2026-02-14T13:00:00Z",
        ),
    ]


@pytest.fixture
def store_with_events(tmp_cortex_home: Path, sample_events: list[Event]) -> tuple[EventStore, str]:
    """Create a store with sample events."""
    config = CortexConfig(cortex_home=tmp_cortex_home)
    project_hash = "test1234test1234"
    store = EventStore(project_hash, config)

    for event in sample_events:
        store.append(event)

    return store, project_hash


# =============================================================================
# Test: generate_decisions_md
# =============================================================================


class TestGenerateDecisionsMd:
    """Tests for generate_decisions_md function."""

    def test_generates_header(self, sample_events: list[Event]) -> None:
        """Generated content includes auto-generated header."""
        from cortex.projections import generate_decisions_md

        result = generate_decisions_md(sample_events)

        assert "auto-generated by Cortex" in result
        assert "Do not edit manually" in result

    def test_includes_decisions(self, sample_events: list[Event]) -> None:
        """Includes decision events in output."""
        from cortex.projections import generate_decisions_md

        result = generate_decisions_md(sample_events)

        assert "SQLite" in result
        assert "✓" in result  # Decision marker

    def test_includes_rejections(self, sample_events: list[Event]) -> None:
        """Includes rejection events in output."""
        from cortex.projections import generate_decisions_md

        result = generate_decisions_md(sample_events)

        assert "PostgreSQL" in result
        assert "✗" in result  # Rejection marker

    def test_excludes_non_decisions(self, sample_events: list[Event]) -> None:
        """Excludes non-decision events."""
        from cortex.projections import generate_decisions_md

        result = generate_decisions_md(sample_events)

        assert "main.py" not in result  # FILE_MODIFIED event

    def test_filters_by_branch(self, sample_events: list[Event]) -> None:
        """Filters decisions by branch when specified."""
        from cortex.projections import generate_decisions_md

        # Add an event from a different branch
        sample_events.append(
            Event(
                type=EventType.DECISION_MADE,
                content="Feature branch decision",
                immortal=True,
                git_branch="feat/test",
            )
        )

        result = generate_decisions_md(sample_events, branch="main")

        assert "Feature branch decision" not in result
        assert "SQLite" in result

    def test_empty_when_no_decisions(self) -> None:
        """Returns placeholder when no decisions exist."""
        from cortex.projections import generate_decisions_md

        events = [Event(type=EventType.FILE_MODIFIED, content="test", immortal=False)]
        result = generate_decisions_md(events)

        assert "No active decisions" in result


# =============================================================================
# Test: generate_archive_md
# =============================================================================


class TestGenerateArchiveMd:
    """Tests for generate_archive_md function."""

    def test_generates_header(self, sample_events: list[Event]) -> None:
        """Generated content includes auto-generated header."""
        from cortex.projections import generate_archive_md

        result = generate_archive_md(sample_events)

        assert "auto-generated by Cortex" in result

    def test_includes_archived_decisions(self, sample_events: list[Event]) -> None:
        """Includes decisions in archive format."""
        from cortex.projections import generate_archive_md

        result = generate_archive_md(sample_events)

        assert "SQLite" in result
        assert "- ✓" in result  # Archive format uses bullet points

    def test_groups_by_month(self, sample_events: list[Event]) -> None:
        """Groups archived decisions by month."""
        from cortex.projections import generate_archive_md

        result = generate_archive_md(sample_events)

        assert "2026-02" in result  # Month header

    def test_empty_when_no_decisions(self) -> None:
        """Returns placeholder when no archived decisions exist."""
        from cortex.projections import generate_archive_md

        events = [Event(type=EventType.FILE_MODIFIED, content="test", immortal=False)]
        result = generate_archive_md(events)

        assert "No archived decisions" in result


# =============================================================================
# Test: generate_plan_md
# =============================================================================


class TestGeneratePlanMd:
    """Tests for generate_plan_md function."""

    def test_generates_header(self, sample_events: list[Event]) -> None:
        """Generated content includes auto-generated header."""
        from cortex.projections import generate_plan_md

        result = generate_plan_md(sample_events)

        assert "auto-generated by Cortex" in result

    def test_includes_active_plan(self, sample_events: list[Event]) -> None:
        """Includes the most recent plan."""
        from cortex.projections import generate_plan_md

        result = generate_plan_md(sample_events)

        assert "Active Plan" in result
        assert "Implement feature X" in result

    def test_includes_completed_steps(self, sample_events: list[Event]) -> None:
        """Includes completed plan steps."""
        from cortex.projections import generate_plan_md

        result = generate_plan_md(sample_events)

        assert "Completed Steps" in result
        assert "- ✓" in result

    def test_empty_when_no_plan(self) -> None:
        """Returns placeholder when no plan exists."""
        from cortex.projections import generate_plan_md

        events = [Event(type=EventType.FILE_MODIFIED, content="test", immortal=False)]
        result = generate_plan_md(events)

        assert "No active plan" in result

    def test_filters_by_branch(self, sample_events: list[Event]) -> None:
        """Filters plan by branch when specified."""
        from cortex.projections import generate_plan_md

        # Add a plan from a different branch
        sample_events.append(
            Event(
                type=EventType.PLAN_CREATED,
                content="Feature branch plan",
                git_branch="feat/test",
                created_at="2026-02-14T14:00:00Z",
            )
        )

        # Without branch filter, shows most recent (feat/test)
        result_all = generate_plan_md(sample_events)
        assert "Feature branch plan" in result_all

        # With branch filter, shows main branch plan
        result_main = generate_plan_md(sample_events, branch="main")
        assert "Feature branch plan" not in result_main


# =============================================================================
# Test: regenerate_all
# =============================================================================


class TestRegenerateAll:
    """Tests for regenerate_all function."""

    def test_creates_projections_dir(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Creates .cortex/ directory if it doesn't exist."""
        from cortex.projections import regenerate_all

        store, _ = store_with_events
        stats = regenerate_all(store, str(tmp_project))

        assert (tmp_project / ".cortex").exists()
        assert len(stats.files_written) == 3

    def test_writes_decisions_file(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Writes decisions.md file."""
        from cortex.projections import regenerate_all

        store, _ = store_with_events
        regenerate_all(store, str(tmp_project))

        decisions_file = tmp_project / ".cortex" / "decisions.md"
        assert decisions_file.exists()
        content = decisions_file.read_text()
        assert "SQLite" in content

    def test_writes_archive_file(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Writes decisions-archive.md file."""
        from cortex.projections import regenerate_all

        store, _ = store_with_events
        regenerate_all(store, str(tmp_project))

        archive_file = tmp_project / ".cortex" / "decisions-archive.md"
        assert archive_file.exists()

    def test_writes_plan_file(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Writes active-plan.md file."""
        from cortex.projections import regenerate_all

        store, _ = store_with_events
        regenerate_all(store, str(tmp_project))

        plan_file = tmp_project / ".cortex" / "active-plan.md"
        assert plan_file.exists()
        content = plan_file.read_text()
        assert "Active Plan" in content

    def test_returns_stats(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Returns statistics about generated projections."""
        from cortex.projections import regenerate_all

        store, _ = store_with_events
        stats = regenerate_all(store, str(tmp_project))

        assert stats.decisions_count == 2  # 1 decision + 1 rejection
        assert stats.plan_steps == 1  # 1 completed step
        assert len(stats.files_written) == 3


# =============================================================================
# Test: should_regenerate
# =============================================================================


class TestShouldRegenerate:
    """Tests for should_regenerate function."""

    def test_true_when_files_missing(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Returns True when projection files don't exist."""
        from cortex.projections import should_regenerate

        store, _ = store_with_events
        result = should_regenerate(store, str(tmp_project))

        assert result is True

    def test_true_when_decisions_exist(self, store_with_events: tuple[EventStore, str], tmp_project: Path) -> None:
        """Returns True when immortal events exist."""
        from cortex.projections import regenerate_all, should_regenerate

        store, _ = store_with_events

        # First, generate the files
        regenerate_all(store, str(tmp_project))

        # Should still return True because decisions exist
        result = should_regenerate(store, str(tmp_project))

        assert result is True


# =============================================================================
# Test: get_projections_dir
# =============================================================================


class TestGetProjectionsDir:
    """Tests for get_projections_dir function."""

    def test_creates_directory(self, tmp_project: Path) -> None:
        """Creates .cortex/ directory if it doesn't exist."""
        from cortex.projections import get_projections_dir

        projections_dir = get_projections_dir(str(tmp_project))

        assert projections_dir.exists()
        assert projections_dir.name == ".cortex"

    def test_returns_existing_directory(self, tmp_project: Path) -> None:
        """Returns existing directory without error."""
        from cortex.projections import get_projections_dir

        # Create directory first
        (tmp_project / ".cortex").mkdir()

        projections_dir = get_projections_dir(str(tmp_project))

        assert projections_dir.exists()


# =============================================================================
# Test: ProjectionStats
# =============================================================================


class TestProjectionStats:
    """Tests for ProjectionStats dataclass."""

    def test_default_values(self) -> None:
        """Has sensible default values."""
        from cortex.projections import ProjectionStats

        stats = ProjectionStats()

        assert stats.decisions_count == 0
        assert stats.archived_count == 0
        assert stats.plan_steps == 0
        assert stats.files_written == []

    def test_initializes_files_written(self) -> None:
        """Initializes files_written to empty list if None."""
        from cortex.projections import ProjectionStats

        stats = ProjectionStats(decisions_count=5)

        assert stats.files_written == []
